---
title: "hw4_2"
output: html_document
---


```{r}
library(lattice)
library(MASS)
library(e1071)
library(corrplot)
library(latticeExtra)
library(boot)
library(mvtnorm)
library(knitr)
library(mvtnorm)
library(plyr)


my.qda <- function(x, data, ...) {
  out <- qda(x, data, ...)
  out$data <- data
  out
}
simple.predict.da <- function(...) predict(...)$class

make.data <- function(groups, model, size, groups.name = "Species") {
  ind <- sample(seq_along(levels(groups)), size = size, replace = TRUE)
  ind = ind[order(ind)]
  res <- data.frame(name = factor(levels(groups)[ind], levels = levels(groups)))
  names(res) <- groups.name
  counter = count(res)[2]
  classes_data = Map(function(i) rmvnorm(counter[i, ], mean = as.numeric(
  model$means[i, ]), sigma = model$cov[[i]]),
  seq_along(levels(groups)))
  classes_data = Reduce(rbind, classes_data)
  res = cbind(res, classes_data)
  colnames(res) <- c(groups.name, colnames(model$cov[[1]]))
  rownames(res) <- NULL
  res
}

```

Вводим модель оценки матриц ковариации отдельно по сортам
```{r}
iris.data <- subset(iris, select = -Species)
means <- aggregate(iris.data, list(groups = iris$Species), mean)
means
covs = by(iris.data, iris$Species, cov)
model <- list(cov = covs, means = means[, -1, drop = FALSE])
```

Данные будем генерировать make.data
Посмотрим, что получилось

```{r}

boot.data <- make.data(iris$Species, model, 300)
splom(iris, groups = iris$Species)
splom(boot.data, groups = boot.data$Species)

```

Далее делаем параметрический бутстраппинг аналогично примеру, только теперь make.data будет генерировать данные на основе model

```{r}

b.model <- boot(iris, function(data) {
  tn <- tune(qda, Species ~ ., data = data, predict.func = simple.predict.da,
  tunecontrol = tune.control(sampling = "fix", fix = 1/2))
  return(tn$best.performance)
  }, R = 999, sim = "parametric", ran.gen = function(data, param) make.data(param$groups, param$model, 300), mle = list(groups = iris$Species,
      model = model))

plot(b.model, index = 1)
```

Нормальности тут явно нет, так что строим перцентильный интервал

```{r}
boot.ci(b.model, type="perc")
```

